import { TableData } from '../Types';

export const data: TableData[] = [
  {
    Pack: 'R10G6M-',
    Descripción: 'Pack 10 GB Internet x 30 días x 6 meses de regalo',
    Otorgado: '17 GB',
    Disponible: '3 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R50G6M',
    Descripción: '3 GB Internet Masivo CR',
    Otorgado: '1 GB',
    Disponible: '2.2192 GB',
    Vencimiento: '06/01/1998 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack Promo Plus de Datos',
    Otorgado: '2 GB',
    Disponible: '12.3467 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack 40 GB Internet x 30 días y wifi gratis',
    Otorgado: '25 GB',
    Disponible: '1 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack 10 GB Internet x 30 días x 6 meses de regalo',
    Otorgado: '22 GB',
    Disponible: '18.455 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack 40 GB Internet x 30 días y wifi gratis',
    Otorgado: '9 GB',
    Disponible: '13 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack 10 GB Internet x 30 días x 6 meses de regalo',
    Otorgado: '6 GB',
    Disponible: '12.666 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack 40 GB Internet x 30 días y wifi gratis',
    Otorgado: '11 GB',
    Disponible: '54.646 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack 10 GB Internet x 30 días x 6 meses de regalo',
    Otorgado: '13 GB',
    Disponible: '4 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack 10 GB Internet x 30 días x 6 meses de regalo',
    Otorgado: '31 GB',
    Disponible: '14.567 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: '3 GB Internet Masivo CR',
    Otorgado: '2 GB',
    Disponible: '5 GB',
    Vencimiento: '05/02/2013 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
  {
    Pack: 'R10G6M',
    Descripción: 'Pack Promo Plus de Datos',
    Otorgado: '4 GB',
    Disponible: '36.781 GB',
    Vencimiento: '05/02/2023 23:59:00',
    'Renov.': '⛑',
    'P. Plus': '⛨',
    id: crypto.randomUUID(),
  },
];
